openapi: 3.0.0
info:
  title: Api kurson serve
  description: Dokumentasi API ini disusun dalam Bahasa Indonesia untuk mempermudah pengguna yang lebih familiar dengan bahasa ini. Kami berusaha memberikan penjelasan yang jelas dan informatif di setiap bagian dokumentasi. Namun, jika terdapat bagian dalam Bahasa Inggris yang kurang tepat atau tidak jelas, kami mohon maaf atas kekurangannya. Jangan ragu untuk memberikan masukan atau pertanyaan kepada kami agar kami dapat terus meningkatkan kualitas dokumentasi ini.
  version: "1.0.2"

servers: 
  - url : https://kursonserver-preview.vercel.app
    description: server preview
  - url : http://localhsot:3000
    description: Local Server
tags:
  - name : Authtentication
    description: for login,signup & user authorization
paths:
  /auth/google:
    get:
      summary: authentication using oauth2 google
      tags: 
        - Authtentication
